from currency_converter import CurrencyConverter
from threading import Event
from random import randint
from utils import clear_terminal


def get_money_interval(difficulty):
    """
    this func checks the current USD-ILS exchange rate, generates a number between 1-101 and multiplies them. also,
    it runs a calculation for setting up the acceptable guess range according to chosen difficulty
    :param difficulty: integer chosen by the player in earlier stage
    :return: a list containing: 1. random number representing the sum (will be printed to the user)
                                2. bottom limit for right guess
                                3. top limit for right guess
    """
    c = CurrencyConverter()

    random_sum = float(randint(1, 101))

    rate = c.convert(1, 'USD', 'ILS')
    rate = round(rate, 2)

    value_to_guess = rate * random_sum

    acceptable_guess_range_top = (value_to_guess - (5 - difficulty))
    acceptable_guess_range_top = round(acceptable_guess_range_top, 2)
    acceptable_guess_range_bottom = (value_to_guess + (5 - difficulty))
    acceptable_guess_range_bottom = round(acceptable_guess_range_bottom, 2)

    return [random_sum, acceptable_guess_range_bottom, acceptable_guess_range_top]


def get_guess_from_user(random_sum, acceptable_guess_range_bottom, acceptable_guess_range_top):
    """
    this func shows the user amount in USD and asks to estimate how much it'll be after converting to ILS
    :param random_sum: an integer between 1-101, generated by get_money_interval func
    :param acceptable_guess_range_top: float number, above this number user guess will be considered wrong
    :param acceptable_guess_range_bottom: float number, below this number user guess will be considered wrong.
    :return: Win (True) or Lose (False)
    """
    clear_terminal()
    print('Welcome to the Currency Roulette Game.\nSoon you will be shown a sum in US Dollars.\n'
          'your task is guessing how much this sum worth in Israeli New Shekel. ')
    Event().wait(5)
    user_guess = input(f'\n\nHow many Israeli Shekels will you get for {random_sum}$? ')
    try:    # trying to catch non number characters
        user_guess = float(user_guess)
    except ValueError:
        print('Oops. Seems like a wrong input. Game Over. ')
        return False
    else:
        if acceptable_guess_range_top >= user_guess >= acceptable_guess_range_bottom:
            print('\nYou are right! ')
            return True
        elif user_guess < acceptable_guess_range_bottom or user_guess > acceptable_guess_range_top:
            print('\nSorry, your answer is too far from the right sum. Game Over. ')
            return False
        else:
            print('\nWrong input. Game Over. ')
            return False


def play_roulette(difficulty):
    """
    this func runs the Currency Roulette game
    :param difficulty:
    :return: True if game won, False if lost
    """
    parameters_list = get_money_interval(difficulty)
    true_of_false = get_guess_from_user(parameters_list[0], parameters_list[2], parameters_list[1])
    if true_of_false:
        return True
    else:
        return False
